// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDduu3HQLcV9yThlen7k3qI6gOs8UJZoBo',
    appId: '1:1072719907973:web:51b4388341ef957241adec',
    messagingSenderId: '1072719907973',
    projectId: 'leroto-job-timer',
    authDomain: 'leroto-job-timer.firebaseapp.com',
    storageBucket: 'leroto-job-timer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz76J_iD23-izEJ6HVnusmWU-LliZAsHo',
    appId: '1:1072719907973:android:600dea8684b845bb41adec',
    messagingSenderId: '1072719907973',
    projectId: 'leroto-job-timer',
    storageBucket: 'leroto-job-timer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUdvQeoKp0j90ZnwFJYjmKkJx32s5esyk',
    appId: '1:1072719907973:ios:f07739a227c8b4aa41adec',
    messagingSenderId: '1072719907973',
    projectId: 'leroto-job-timer',
    storageBucket: 'leroto-job-timer.appspot.com',
    iosClientId: '1072719907973-9u9t817fqhei8nbqbt0pp77m1kf3etf6.apps.googleusercontent.com',
    iosBundleId: 'br.com.jobtimer.jobTimer',
  );
}
